apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sb-post-install 
  janus-idp.io/tekton: sb-post-install
  backstage.io/kubernetes-id: sb-post-install
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sb-post-install
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  