apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sb-post-install
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sb-post-install 
  name: sb-post-install
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sb-post-install 
