apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sb-post-install-gitops
  description: This is GitOps manifest for sb-post-install   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: sb-post-install
    janus-idp.io/tekton: sb-post-install 
    backstage.io/kubernetes-id: sb-post-install 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sb-post-install
